module:
  admin_toolbar: 0
  backup_migrate: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  context: 0
  context_ui: 0
  contextual: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_collection: 0
  field_ui: 0
  file: 0
  filter: 0
  filter_perms: 0
  image: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  path: 0
  redirect: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  bartik: 0
  sacredhands: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
