features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/sacredhands/logo.png
favicon:
  use_default: 0
  path: themes/custom/sacredhands/favicon.png
  mimetype: image/png
